default: true

# MD013/line-length - Line length
MD013:
  line_length: 999
  heading_line_length: 120
  code_block_line_length: 120
  code_blocks: true
  tables: false
  headings: true
  strict: false
  stern: false

MD029: false
